### ISSUE TITLE
TypeError: process.argv.contains is not a function

### ISSUE THREAD

**Issue by soenkekluth** [aikar/create-flow-pkg#2]
```shell
create-flow-pkg initlib --browser
/usr/local/lib/node_modules/create-flow-pkg/create-flow-pkg.js:23
        util.updatePackageJson(isLib, isLib && process.argv.contains("--browser"));
                                                            ^

TypeError: process.argv.contains is not a function
    at Object.<anonymous> (/usr/local/lib/node_modules/create-flow-pkg/create-flow-pkg.js:23:61)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
```

**Comment by soenkekluth** [comment]
❯ node --version
v9.2.0
