### ISSUE TITLE
cp: the -R and -r options may not be specified together.

### ISSUE THREAD

**Issue by soenkekluth** [aikar/create-flow-pkg#3]
```shell
❯ create-flow-pkg initapp
....
...
[install dev deps] Done in 56.68s.
cp: the -R and -r options may not be specified together.
child_process.js:614
    throw err;
    ^

Error: Command failed: cp -ar '/usr/local/lib/node_modules/create-flow-pkg/skel/.babelrc.js' '.'
cp: the -R and -r options may not be specified together.

    at checkExecSyncError (child_process.js:574:11)
    at execSync (child_process.js:611:13)
    at exec (/usr/local/lib/node_modules/create-flow-pkg/create-flow-pkg-util.js:16:20)
    at Object.cpSkeleton (/usr/local/lib/node_modules/create-flow-pkg/create-flow-pkg-util.js:98:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/create-flow-pkg/create-flow-pkg.js:25:14)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
```

**Comment by soenkekluth** [comment]
good boy. will test. thanks for your open source

**Comment by aikar** [comment]
@soenkekluth I'm not sure it's going to fix it. my assumption is that you have an alias on your system like `alias cp="cp -R" which triggered it, as if you view the source code, I clearly do not have both -r and -R.

So this change will ignore user aliases by invoking /bin/cp

Version 1.0.10

**Comment by soenkekluth** [comment]
@aikar i will check. but i am pretty sure i did not alias cp itself -  to be independent from all this and to satisfy all our platforms i would recommend using https://github.com/shelljs/shelljs - cross platform unix commands. just say a word - I can implememt it and make a PR

**Comment by soenkekluth** [comment]
ps. I am thinking about making a CLI for project setups that gives you more and hopefully  all flexibility to 1. choose one like yours from a list / add your own configs and dependencies (also add it to the CLI apps db. ) - and - not to  be just like yo 2,0 - merge your needs into another setuo from the CLI's db. or making it a module / middleware / plugin. if your interested we can do it together
